#define MAJ_CONSOLE  1
#define MAJ_NETIF    2
#define MAJ_SAMPLER  3
#define MAJ_LOCKSTAT 4
#define MAJ_STAT     5
#define MAJ_CMDLINE  6
#define MAJ_GC       7
#define MAJ_KCONFIG  8
#define MAJ_KSTATS   9
#define MAJ_KMEMSTATS 10
